### ISSUE TITLE
Getting Invalid Argument to -A when trying to disable attributelogs

### ISSUE THREAD

**Issue by anurag-bug** [smartmontools/smartmontools#115]
service smartmontools start

smartd_opts='--interval=1800 -A "" '

![image](https://user-images.githubusercontent.com/29235137/141122385-78ef6b7c-fd5f-43f3-aa0a-29ca57defbc2.png)

Error: relative path names are not allowed

OS 
NAME="Ubuntu"
VERSION="14.10 (Utopic Unicorn)"

**Comment by chrfranke** [comment]
It is (AFAIK) not possible to pass empty arguments indirectly via `$smartd_opts`.

Possible workaround for systems with `systemd` (not tested): Install a custom `/etc/systemd/system/smartd.service` file as a copy of `/lib/systemd/system/smartd.service` with the following change:
```diff
- ExecStart=/usr/sbin/smartd -n $smartd_opts
+ ExecStart=/usr/sbin/smartd -n -A "" $smartd_opts
```
and set `smartd_opts='--interval=1800'`.

(Note: Some distributions use `smartmontools.service` instead of `smartd.service`)

**Comment by chrfranke** [comment]
Added ability to use `-A -` instead in [r5245](https://www.smartmontools.org/changeset/5245) (b6d74bf).

**Comment by chrfranke** [comment]
A late followup: It may also be possible to pass an empty string without any workaround by using the long option instead:

`smartd_opt='--interval=1800 --attributelog='`

This may not work with all variants of `getopt_long()` library function.
