### ISSUE TITLE
Limit or spread performance impact of running smartctl on HDDs

### ISSUE THREAD

**Issue by patrakov** [smartmontools/smartmontools#158]
When running `smartctl -a /dev/sda` on an HDD, it has measurable performance impact on the IOPS. The graph below is for a Seagate ST18000NM0092-3CX103 SATA drive, on a misconfigured system that runs `smartctl -a /dev/sda` every two minutes. The benchmark is a `fio` benchmark for random reads with 4 jobs, iodepth=4, and block size 4k. For random writes, it is even worse.

![image](https://user-images.githubusercontent.com/2943163/205139100-a8524c0d-a04f-41d5-a373-7401442150ae.png)

If getting the SMART report takes multiple `ioctl` calls, maybe it makes sense to try, optionally (if enabled via some new command-line argument), inserting some sleeps between them, to spread the impact over time? I don't know if the idea works, but I am willing to test patches.

**Comment by chrfranke** [comment]
This is not unexpected. All (S)ATA commands issued by smartctl are slow synchronous ("PIO", name inherited from PATA/IDE) commands. Asynchronous ("DMA") or queued ("FPDMA QUEUED" aka "NCQ") versions of SMART related commands are not available. Before issuing such a command, the kernel likely needs to stop queuing I/O requests to the device and wait for their completion. After issuing such a command, the queue needs some time to "warm up" again.

You could check `ioctl()` duration with for example
```
smartctl -a -r ioctl /dev/sda | grep -E 'Command=|Duration:'
```
To reduce the number of slow `ioctl()` calls from 8 to 4, omit the (legacy) logs from the output:
```
smartctl -i -H -c -A /dev/sda
```

Adding a delay between the `ioctl()` calls is possibly counter productive because the queue "cool downs" and "warm ups" will happen several times. If you want to test this, try this simple patch:
```diff
Index: atacmds.cpp
===================================================================
--- atacmds.cpp (revision 5419)
+++ atacmds.cpp (working copy)
@@ -20,6 +20,7 @@
 #include <errno.h>
 #include <stdlib.h>
 #include <ctype.h>
+#include <unistd.h>

 #include "atacmds.h"
 #include "knowndrives.h"  // get_default_attr_defs()
@@ -575,6 +576,7 @@

     if (ata_debugmode && out.out_regs.is_set())
       print_regs(" Output: ", out.out_regs);
+    usleep(10*1000); // wait 10ms

     if (ok) switch (command) {
       default:
```

**Comment by chrfranke** [comment]
The performance impact is likely the result of the legacy "PIO" ATA commands which are required for SMART access (see previous comment). There are no alternatives so this cannot be fixed by smartctl.
