### ISSUE TITLE
Excessively flagged on VirusTotal

### ISSUE THREAD

**Issue by jpele-tis** [smartmontools/smartmontools#207]
Hello,
The latest Windows release (smartmontools-7.4-1.win32-setup.exe) is Excessively flagged on VirusTotal:
https://www.virustotal.com/gui/file/76880e7303403667739066782b1c458ede2b4462a8ebd6aeacf97efecd4bdde7?nocache=1

**Comment by chrfranke** [comment]
This is the false positive mess which often appeared after new releases. This time more than usual, possibly because we updated our cross toolchains.

The following vendors have already confirmed this as a false positive: Bitdefender (which inherited the FP to Emsisoft, eScan, GData, Trellix), McAfee, Microsoft, SecureAge.

No reply from "Rising" since August, 2nd, see http://mailcenter.rising.com.cn/filecheck_en/ and enter
_Inquiries Number: RS20230803012529148447_.

The remaining vendors do not provide an easy way to report FPs for non-customers, see [False-Positive-Center](/yaronelh/False-Positive-Center).

Note that there is no actual Windows involved in the build process of release and CI builds for Windows. All are done with MinGW-w64 and NSIS cross-toolchains using a Linux Docker image, see https://builds.smartmontools.org/

**Comment by jpele-tis** [comment]
Hello @samm-git, @chrfranke,
Why has this issue been marked as completed, the file is still flagged by 6/68 security vendors
Regards,
Jimmy
