### ISSUE TITLE
Remaining Lifetime calculation wrong? (CT1000MX500SSD1)

### ISSUE THREAD

**Issue by Giga-Pudding** [smartmontools/smartmontools#296]
Hello,

i have stumbled upon something strange. I have a Crucial 1TB SSD here (CT1000MX500SSD1).
smartctl reports 19% lifetime remaining. But that seems to be wrong:

Sector Sizes: 512 bytes logical / 4096 bytes physical
S.M.A.R.T. Attribute 246 (Total Host Sectors Written): 23,996,625,190

23,996,625,190 * 4096 bytes = 98,290,176,778,240 bytes (or 98,2 terabytes).
But [the specifications](https://content.crucial.com/content/dam/crucial/ssd-products/mx500/flyer/crucial-mx500-ssd-productflyer-en.pdf) on the crucial website reports 360 TBW endurance for this SSD.

So if i am not mistaken, it's actually 72.69 % lifetime remaining.
Was my calculation wrong or does smartctl report a false % value?

**Comment by chrfranke** [comment]
Smartctl never calculates lifetimes, it only prints the value reported by the drive. Raw attribute values are vendor and device specific. Such host R/W counts may use different units (LBA, MiB, GiB, ...). I never seen a device which counts PBA.

In this case it is likely a LBA count: 23996625190 * 512 = 12286272097280 = ~12.3TB
If you really trust the 360 TBW (I won't), this would mean ~3.4% lifetime _used_.

Don't use `smartctl -a` as it only contains  legacy (and officially obsoleted) SMART information. Always use `smartctl -x` instead. It may contain `Device Statistics` with a more reliable count.

For further diagnostics, please provide a `smartctl -x -a ...` output of this device.

**Comment by Giga-Pudding** [comment]
Hi Christian,

thanks for you super quick response and thank you for your help!

Using PBA for the calculation was my assumption. It seemed more plausible to me. I'm not very deep into storage, but if i remember correctly, the physical sector size is the smallest amount of data that can be written. It's not possible to only write 512 bytes, if the physical sector size is 4096 bytes, right?

Anyway, i've attached the output of smartctl -x -a
Please note, that i have used the slightly older smartctl version 7.2

[ssd-smart-values.txt](https://github.com/user-attachments/files/17684915/ssd-smart-values.txt)

**Comment by chrfranke** [comment]
> It's not possible to only write 512 bytes, if the physical sector size is 4096 bytes, right?

Not right. The OS uses logical block size and addresses using LBA. The larger physical block size mentioned is only a hint that it is not recommended to do multi sector transfers not aligned to this boundary. Was an issue with early 4KiB/512B PBS/LBS HDDs (Marketing noise: "Advanced Format") if traditional MBR partitioning is still used (first partition starts at LBA 63 - first cylinder, second head, first sector of a legacy HDD).

I guess the PBS is mostly a fake info here because (AFIAK) SSD internally manages flash in much larger blocks.

The device actually reports 81% lifetime _used_ (`RAW_VALUE`), 19% _remaining_ (normalized `VALUE`), the `SMART Attributes` are consistent with `Device Statistics`. But `246 Total_LBAs_Written` and `Logical Sectors Written` differ considerably (Factor ~9.5):

```
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
...
202 Percent_Lifetime_Remain ----CK   019   019   001    -    81
...
246 Total_LBAs_Written      -O--CK   100   100   000    -    23996625190
...
Device Statistics (GP Log 0x04)
Page  Offset Size        Value Flags Description
0x01  =====  =               =  ===  == General Statistics (rev 1) ==
...
0x01  0x018  6      2521788710  ---  Logical Sectors Written
...
0x07  =====  =               =  ===  == Solid State Device Statistics (rev 1) ==
0x07  0x008  1              81  ---  Percentage Used Endurance Indicator
```
You should possibly schedule a replacement of this drive.

**Comment by Giga-Pudding** [comment]
Hi Christian,

thanks for clarifying things.
Excuse me for creating this issue, i was falsely thought, that smartctl would calculate the lifetime somehow instead.

Again, thanks for explaining everything to me :)
