### ISSUE TITLE
SMART Automatic Offline Testing unsupported - enabled SMART Automatic Offline Testing.

### ISSUE THREAD

**Issue by Pascal666** [smartmontools/smartmontools#50]
In /var/log/messages:
```
Mar  5 18:27:51 localhost smartd[9867]: Device: /dev/sdm [SAT], SMART Automatic Offline Testing unsupported...
Mar  5 18:27:51 localhost smartd[9867]: Device: /dev/sdm [SAT], enabled SMART Automatic Offline Testing.
```
Manual test:
```
# smartctl -o on /dev/sdm
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-3.10.0-1062.4.1.el7.x86_64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Automatic Timers not supported

SMART Automatic Offline Testing Enabled every four hours.
```

I'm thinking it probably shouldn't be reporting enabled, if it is unsupported.

**Comment by chrfranke** [comment]
This is intentional since [r796](https://www.smartmontools.org/changeset/769/trunk/sm5/smartd.c). Note that the command _SMART ENABLE/DISABLE AUTOMATIC OFF-LINE_ and the related 'supported' bit was never part of any version of the ATA standard (see smartctl and smartd.conf man pages). Drives may implement this command even if the bit is not set. Therefore the command is issued unconditionally.

I will not change this longstanding behavior without an important reason.
