### ISSUE TITLE
Why does this wake up the drive? smartctl -i -n standby /dev/sdx

### ISSUE THREAD

**Issue by zvargams** [smartmontools/smartmontools#57]
The way I see this command should leave the disk spun down:

> -n POWERMODE, --nocheck=POWERMODE
> 
> standby - check the device unless it is in SLEEP or STANDBY mode. In these modes most disks are not spinning, so if you want to prevent a disk from spinning up, this is probably what you want. 

--

Still, in my case (SATA drive in a USB enclosure) this command will wake up a WD MyBook:

```
`root@odroidn2:/root# smartctl -i -n standby /dev/sdc
smartctl 7.1 2019-12-30 r5022 [aarch64-linux-4.9.219-meson64] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

Device is in SLEEP mode, exit(2)
`
```

Drive starts up, needs a few seconds...

Then:

```
`root@odroidn2:/root# smartctl -i -n standby /dev/sdc
smartctl 7.1 2019-12-30 r5022 [aarch64-linux-4.9.219-meson64] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     WDC HGST Ultrastar He10
Device Model:     WDC WD80EZAZ-11TDBA0
Serial Number:    xxx
LU WWN Device Id: 5 000cca 257e79007
Firmware Version: 83.H0A83
User Capacity:    8,001,563,222,016 bytes [8.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Wed Jul  8 15:45:05 2020 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
Power mode is:    ACTIVE or IDLE
`
```
What am I missing here? At first it does recognize the drive is in SLEEP, but still triggers a spin-up? Thanks for your review!

**Comment by samm-git** [comment]
USB host enclosure often managing sleep state on its own, so it can send sleep or wakeup commands without any OS knowledge about it. Most likely it is the case here.

**Comment by zvargams** [comment]
Alright, so likely nothing can be done here from smartmontools perspective..?

**Comment by jenshenk** [comment]
Google sent me here :) very old post but just my two cents:
Every external WD I bought so far that I wanted to use for my Raspi powered NAS I ended up putting into a cheap new case (got a bunch from sharkoon) since WD seems to add some unnecessary stuff on their controllers that can't be controlled. I just bought a new one and thought I could make it work, but after a few days of a lot of investigating I noticed the most silly thing is that some function from the case actually makes the disk spin up without the OS noticing. This leads to the disk just keep on spinning until you access it again what the OS identifies as spin up. 
Furthermore: What you encountered is especially bad, since for the OS the drive still looks to be in standby - I noticed even if you do a smartctl check without the -n standby the OS might not see the drive as spun up. The only way I found work is to make smartctl ignore external drives, do smart checks via cron every few days (I write the output to local website), and create a dummy file on the drive so that the os notices access to the drive

**Comment by bverkron** [comment]
> USB host enclosure often managing power state on its own, so it can send sleep or wakeup commands without any OS knowledge about it. Most likely it is the case here.

I have a WD D10 external USB drive and indeed `smartctl` wakes it with the same command as OP even though it's not supposed to.

It could be due to something in the enclosure hardware as stated by @samm-git but it's definitely 100% correlated to when I issue the `smartctl` command and not due to the drive just randomly waking itself. I have tried all kinds of different wait intervals before issuing the `smartctl` command (after forcing the drive to sleep) and every time without fail the second I issue the `smartctl` command the drive spins up. Bummer.

**Comment by samm-git** [comment]
@bverkron adding more comments like that would not help for sure. Issue is closed, problem is on WD side, nothing we can do.
