### ISSUE TITLE
[Question] Version of smartmon and drivedb.h

### ISSUE THREAD

**Issue by malvinas2** [smartmontools/smartmontools#80]
Probably a greenhorn question: 
In case I got stucked to `Ubuntu Xenial Xerus 16.04.7 LTS` and `smartmontools 6.4 (6.5?)`, do I have to use the corresponding release of `drivedb.h` (here: 6.4 [https://www.smartmontools.org/browser/branches/RELEASE_6_4_DRIVEDB/smartmontools/drivedb.h](https://www.smartmontools.org/browser/branches/RELEASE_6_4_DRIVEDB/smartmontools/drivedb.h) or can I use the newest release of `drivedb.h` (7.0/7.1 [https://www.smartmontools.org/browser/branches/RELEASE_7_0_DRIVEDB/smartmontools/drivedb.h](https://www.smartmontools.org/browser/branches/RELEASE_7_0_DRIVEDB/smartmontools/drivedb.h)  ?

```
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.15.0-96-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org
....
smartmontools release 6.5 dated 2015-06-04 at 16:29:41 UTC
smartmontools SVN rev 4214 dated 2016-01-24 at 22:53:37
smartmontools build host: x86_64-pc-linux-gnu
smartmontools build with: GCC 5.4.0 20160609
```
(BTW: Why does it say 'release 6.5' if newest version available for Xenial is 6.4 ? [https://packages.ubuntu.com/xenial/smartmontools](https://packages.ubuntu.com/xenial/smartmontools))

**Comment by chrfranke** [comment]
We traditionally (since 2002) bump release numbers immediately after each release, such that releases from intermediate SVN snapshots have a greater release number than possibly expected. Release 6.4 is [r4109](https://www.smartmontools.org/changeset/4109), Release 6.5 is [r4318](https://www.smartmontools.org/changeset/4318).

smartmontools 6.5 adds the no backward compatible `DEFAULT` entry to drivedb.h in [r4162](https://www.smartmontools.org/changeset/4162), so it should be safe to use the 6.5 drivedb branch on this (r4214) snapshot release. Using the 7.0 branch would fail if `-d sntjmicron` USB device type is detected.
